config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :taxons do
      get :children, :on => :member
    end

    resources :taxonomies do
      resources :taxons
    end
  end


  root :to => "admin/taxonomies#index"
  
end

app/models/taxon.rb
require 'taxis/taxon'
class Taxon < Taxis::Taxon
  
end

app/models/taxon_item.rb
require 'taxis/taxon_item'
class TaxonItem < Taxis::TaxonItem
  
end

app/models/taxonomy.rb
require 'taxis/taxonomy'
class Taxonomy < Taxis::Taxonomy
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  include Taxis::ControllerHelpers

  # For the gem
  unloadable



  protected



end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < Admin::BaseController


  def index
    @taxonomies = Taxonomy.all 
  end

  def show
    @taxonomy = Taxonomy.find(params[:id])
  end

  def new
    @taxonomy = Taxonomy.new
  end

  def create
    @taxonomy = Taxonomy.new(params[:taxonomy])
    if @taxonomy.save
      redirect_to edit_admin_taxonomy_url(@taxonomy), :notice => "Successfully created taxonomy."
    else
      render :action => 'new'
    end
  end

  def edit
    @taxonomy = Taxonomy.find(params[:id])
    @tree = root_tree(@taxonomy)
  end

  def update
    @taxonomy = Taxonomy.find(params[:id])
    if @taxonomy.update_attributes(params[:taxonomy])
      redirect_to admin_taxonomies_url, :notice  => "Successfully updated taxonomy."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @taxonomy = Taxonomy.find(params[:id])
    @taxonomy.destroy
    redirect_to admin_taxonomies_url, :notice => "Successfully destroyed taxonomy."
  end
  

  private

  def root_tree(taxonomy)
    tree = {
      :attr => {:id => taxonomy.root.id.to_s, :rel => "root"},
      :data => taxonomy.root.name,
      :state => "open",
      :children => tree_children(taxonomy.root)
    }
    return tree
  end

end

app/controllers/admin/taxons_controller.rb
class Admin::TaxonsController < Admin::BaseController

  before_filter :find_taxonomy, :except => [:children]

  def index

    if @taxonomy
      @taxons = @taxonomy.children.order(:pos)
    else
      @taxons = Taxon.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @taxons}
    end
    
    
  end

  def show
    @taxon = Taxon.find(params[:id])
  end

  def new
    @taxon = Taxon.new
  end

  def create
    @taxon = Taxon.new(params[:taxon])
    if @taxon.save
      redirect_to edit_admin_taxonomy_url(@taxon.taxonomy), :notice => "Successfully created taxon."
    else
      render :action => 'new'
    end
  end

  def edit
    @taxon = Taxon.find(params[:id])
    @taxonomy = @taxon.taxonomy
  end

  def update
    @taxon = Taxon.find(params[:id])
    if @taxon.update_attributes(params[:taxon])

      # Move the taxon to the correct position
      if params[:left_of_id] != params[:parent_id]
        @right_taxon = Taxon.find(params[:left_of_id])
        @taxon.move_to_left_of(@right_taxon) if @right_taxon && @taxon.siblings.include?(@right_taxon)
      end

      if params[:format] == :json
        render :json => "ok"
      else
        redirect_to edit_admin_taxonomy_url(@taxon.taxonomy), :notice  => "Successfully updated taxon."
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @taxon = Taxon.find(params[:id])
    @taxon.destroy
    redirect_to edit_admin_taxonomy_url(@taxon.taxonomy), :notice => "Successfully destroyed taxon."
  end


  # Action for getting the children of a taxon
  # right now it only responds to json requests
  def children
    @taxon = Taxon.find params[:id]
    @children = @taxon.children
    @tree = tree_children(@taxon)
    respond_to do |format|
      format.html
      format.json { render :json => @tree }
    end
    
  end

  # Attach a class to a taxon
  # params should have a class name, i.e. 'Product'
  # and an id.
  # In the view you should send params like :attach_class => 'Product', :attach_id => 1
  def attach
    @taxon = Taxon.find params[:id]
    result = nil
    begin
      @taxon.attach_by_param(params[:attach_class], params[:attach_id])
      result = "ok"
    rescue
      result = "Invalid parameters"
    end
    
    if params[:format] == :json
      render :json => result
    else
      redirect_to edit_admin_taxonomy_url(@taxon.taxonomy), :notice => result
    end
  end

  # Detach a class from a taxon
  # params should have a class name, i.e. 'Product'
  # and an id.
  # In the view you should send params like :attach_class => 'Product', :attach_id => 1
  def detach
    @taxon = Taxon.find params[:id]
    result = nil
    begin
      @taxon.detach_by_param(params[:attach_class], params[:attach_id])
      result = "ok"
    rescue
      result = "Invalid parameters"
    end
    
    if params[:format] == :json
      render :json => result
    else
      redirect_to edit_admin_taxonomy_url(@taxon.taxonomy), :notice => result
    end
  end

  private 

  def find_taxonomy
    if params[:taxonomy_id]
      @taxonomy = Taxonomy.find(params[:taxonomy_id]) 
    else
      @taxonomy = nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/views/admin/taxonomies/_form.html.erb
<p>
  <%= f.label :name, "Name" %> <span class="required">*</span><br />
  <%= text_field :taxonomy, :name  %>
</p>

app/views/admin/taxonomies/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_id = #{@taxonomy.id};
    var loading = '#{escape_javascript t('loading')}';
    var new_taxon = '#{escape_javascript t('new_taxon')}';
    var server_error = '#{escape_javascript t('server_error')}';
    var taxonomy_tree_error = '#{escape_javascript t('taxonomy_tree_error')}';"
  %>
  <%= javascript_include_tag 'taxonomy', 'jsTree/jquery.jstree.js' %>
<% end %>

app/views/admin/taxonomies/_list.html.erb
<table class="index" id='listing_taxonomies'>
  <tr>
    <th><%= "Name" %></th>
    <th>&nbsp;</th>
  </tr>
<% for taxonomy in @taxonomies %>
  <tr id="<%= dom_id taxonomy %>">
	  <td>
	    <%= taxonomy.name %>
    </td>
    <td class="actions">
      <%= link_to "Edit", edit_admin_taxonomy_url(taxonomy.id), :class => 'edit' %>
      &nbsp;
      <%= link_to "Delete", admin_taxonomy_path(taxonomy), :confirm => 'Are you sure?', :method => :delete %>
      
    </td>
  </tr>
<% end %>
</table>

app/views/admin/taxonomies/edit.erb
<%= render :partial => "js_head" %>

<h1>Edit Taxonomy</h1>

<p id="ajax_error" class="errorExplanation" style="display:none;"></p>

<%= form_for(:taxon, :url => admin_taxonomy_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
	  <div>
	    <label>Taxonomy Tree</label><br />
      <div id="taxonomy_tree" class="tree"></div>
  	</div>
  	<p id="progress" style="display:none;">
       <%= image_tag('spinner.gif', :alt =>  "Spinner", :style => "vertical-align:bottom") %>
       Updating...
    </p>

	<p class="form-buttons">
	  <%= f.submit %> <%= link_to "Back to Taxonomies", admin_taxonomies_path %>
  </p>
<% end %>


<% content_for :head do %>
  <script type="text/javascript">
    var initial = <%= raw @tree.to_json %>;

  </script>
<% end %>

app/views/admin/taxonomies/index.html.erb
<h1>Taxonomies</h1>

<div id='list-taxonomies'>
	<%= render :partial => 'list' %>
</div>

<%= link_to "New Taxonomy", new_admin_taxonomy_url %>

app/views/admin/taxonomies/new.html.erb
<h1>New Taxonomy</h1>

<%= form_for(:taxonomy, :url => '/admin/taxonomies') do |f| %>

	<%= render :partial => "form", :locals => { :f => f } %>

	<p class="form-buttons">
	  <%= f.submit %> or <%= link_to "Cancel", admin_taxonomies_url %>
  </p>
<% end %>

app/views/admin/taxons/_form.html.erb
<%= @taxon.path %><br />
<%= f.label :name, "Name" %> <span class="required">*</span><br />
<%= text_field :taxon, :name  %>

app/views/admin/taxons/_taxon_table.html.erb
<table class="index">
  <thead>
  	<tr>
  		<th>Name</th>
  		<th>Path</th>
  		<th></th>
  	</tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon)%>">
        <td><%= taxon.name %></td>
        <td><%= taxon.path %></td>
  	    <td class="actions">	                         
		      <%#= link_to_delete taxon, :url => remove_admin_product_taxon_url(@product, taxon), :name => icon("delete") + ' ' + t("remove") %>
  	    </td>        
      </tr>
    <% end %>
    <% if taxons.empty? %>
     <tr><td colspan="3">None</td></tr>
    <% end %>
  </tbody>
</table>

app/views/admin/taxons/edit.html.erb
<h1>Edit Taxon</h1>

<%= form_for(:taxon, :url => admin_taxon_url, :html => { :method => :put, :multipart => true}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <p class="form-buttons">
    <%= f.submit %> or <%= link_to "Cancel", edit_admin_taxonomy_url(@taxonomy) %>
  </p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title><%= "Taxonomy Admin" %> </title>

  <%= javascript_include_tag 'jquery.min.js', 'rails' %>
  <%= javascript_tag "$ = jQuery;" %>
  <%= csrf_meta_tag %>
  <%= yield :head %>

</head>
<body >


    <% if flash[:error] %>
      <div class="flash error"><%= flash[:error] %></div>
    <% end %>
    <% if self.notice %>
      <div class="flash notice"><%= self.notice %></div>
    <% end %>


    <%= yield %>

</body>
</html>